import React from 'react';
import { Trash2, ShoppingBag, Share2, X } from 'lucide-react';

const MarketList = ({ list, onRemove, onClear }) => {
  // 1. Generate the WhatsApp URL outside the click handler
  const message = `🛍️ *My Kitchen Companion Market List*:\n\n${list
    .map((item, i) => `${i + 1}. ${item}`)
    .join('\n')}\n\n_Generated by My Pantry Guide_`;
  
  const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(message)}`;

  return (
    <div className="max-w-2xl mx-auto p-4 md:p-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex items-center justify-between mb-8">
        <div>
          <h2 className="text-3xl font-black text-slate-900 tracking-tight">Market List</h2>
          <p className="text-sm text-slate-400 font-medium">You have {list.length} items to buy</p>
        </div>
        
        {list.length > 0 && (
          <button 
            onClick={onClear}
            className="flex items-center gap-2 px-4 py-2 text-red-500 hover:bg-red-50 rounded-xl transition-colors text-xs font-black uppercase tracking-widest"
          >
            <Trash2 size={16} />
            Clear All
          </button>
        )}
      </div>

      {list.length > 0 ? (
        <div className="space-y-4">
          <div className="grid gap-3">
            {list.map((item, index) => (
              <div 
                key={index} 
                className="group flex items-center justify-between p-5 bg-white border border-slate-100 rounded-3xl shadow-sm hover:border-orange-200 hover:shadow-md transition-all"
              >
                <div className="flex items-center gap-4">
                  <div className="w-2 h-2 bg-orange-500 rounded-full" />
                  <span className="font-bold text-slate-700">{item}</span>
                </div>
                <button 
                  onClick={() => onRemove(item)}
                  className="p-2 text-slate-300 hover:text-red-500 hover:bg-red-50 rounded-lg transition-all"
                >
                  <X size={18} />
                </button>
              </div>
            ))}
          </div>

          {/* 2. Changed from <button> to <a> for Vercel production stability */}
          <a 
            href={whatsappUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="w-full mt-8 flex items-center justify-center gap-3 bg-[#25D366] text-white py-5 rounded-[28px] font-black text-sm uppercase tracking-widest hover:scale-[1.02] active:scale-95 transition-all shadow-xl shadow-green-100"
          >
            <Share2 size={20} />
            Send to WhatsApp
          </a>
        </div>
      ) : (
        <div className="flex flex-col items-center justify-center py-24 bg-slate-50/50 rounded-[40px] border-2 border-dashed border-slate-100">
          <div className="w-20 h-20 bg-white rounded-3xl flex items-center justify-center shadow-sm mb-6">
            <ShoppingBag size={40} className="text-slate-200" />
          </div>
          <p className="text-slate-400 font-bold uppercase tracking-widest text-[10px]">Your list is empty</p>
          <p className="text-slate-300 text-sm mt-2">Add ingredients from any recipe to see them here.</p>
        </div>
      )}
    </div>
  );
};

export default MarketList;